/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 model.glb 
Author: eb78 (https://sketchfab.com/E.A.Cornell)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/ulysses-butterfly-1155effb97564974aa0553db3d5eed57
Title: Ulysses Butterfly
*/

import React, { useRef ,useEffect} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model({onClick, setActions, ...props }) { //change this one  for animation 
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/car/model.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    // Play a specific animation by name
    // actions['fly'].play()

    setActions(actions);  // for animaiton sett

    // Optional: Stop the animation when the component unmounts
    // return () => actions['fly'].stop()
  }, [actions])


  return (
    <group ref={group} {...props}  onClick={onClick}   dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={23.235}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Armature_63" scale={0.03}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.UlyssesButterfly_mat} skeleton={nodes.Object_7.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/car/model.glb')

export default Model